// Used by CI (`npx eslint`); the app itself has no dependencies. Catches what a split into modules can break: a name that is used but
// never imported (a ReferenceError the first time that screen is opened), imports nobody uses, and common slips.
const browser = Object.fromEntries(['window', 'document', 'navigator', 'location', 'history', 'localStorage', 'sessionStorage', 'matchMedia', 'fetch', 'EventSource', 'WebSocket', 'URL', 'URLSearchParams', 'Blob', 'File', 'FileReader', 'FormData', 'DataTransfer', 'Notification', 'MutationObserver', 'ResizeObserver', 'IntersectionObserver', 'CustomEvent', 'KeyboardEvent', 'Event', 'Node', 'NodeFilter', 'Element', 'HTMLElement', 'HTMLAnchorElement', 'TextDecoder', 'TextEncoder', 'AbortController', 'console', 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'requestAnimationFrame', 'cancelAnimationFrame', 'getComputedStyle', 'alert', 'Terminal', 'FitAddon', 'Intl', 'Promise', 'performance', 'queueMicrotask', 'structuredClone', 'atob', 'btoa', 'CSS', 'Image', 'Audio', 'Option', 'XMLHttpRequest', 'innerHeight', 'innerWidth', 'crypto', 'addEventListener', 'removeEventListener', 'prompt', 'confirm'].map((k) => [k, 'readonly']))
const node = Object.fromEntries(['process', 'Buffer', 'console', 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'URL', 'URLSearchParams', 'fetch', 'AbortController', 'TextDecoder', 'TextEncoder', 'WebSocket', 'structuredClone', 'queueMicrotask', 'Intl'].map((k) => [k, 'readonly']))
const rules = { 'no-undef': 'error', 'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true }], 'no-dupe-keys': 'error', 'no-dupe-else-if': 'error', 'no-unreachable': 'error', 'no-redeclare': 'error', 'no-const-assign': 'error', 'no-self-assign': 'error', 'no-func-assign': 'error', 'no-import-assign': 'error', 'no-duplicate-imports': 'error', 'no-unsafe-finally': 'error', 'no-loss-of-precision': 'error', 'no-sparse-arrays': 'error', 'use-isnan': 'error', 'valid-typeof': 'error' }
export default [
  { ignores: ['public/vendor/**', 'dist/**', 'node_modules/**'] },
  { files: ['public/**/*.js'], languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: browser }, rules },
  { files: ['server.js', 'bin/**'], languageOptions: { ecmaVersion: 2024, sourceType: 'commonjs', globals: { ...node, __dirname: 'readonly', __filename: 'readonly', require: 'readonly', module: 'writable' } }, rules },
  { files: ['tests/**/*.mjs'], languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: { ...node, ...browser, document: 'readonly', window: 'readonly' } }, rules: { ...rules, 'no-undef': 'error', 'no-unused-vars': 'off' } }
]
